config/routes.rb
Rails.application.routes.draw do

  resources :cards do
    resources :comments
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users
  resources :welcome

  root 'welcome#index'

end

app/models/card.rb
class Card < ActiveRecord::Base

	belongs_to :user

	has_many :comments, dependent: :destroy
	
	validates :subject, presence: true,
		length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :card
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :cards,

	has_secure_password

	def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

	validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	def authorize
		redirect_to login_url, alert: "Not authorized" if current_user.nil?
	end

	private
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

	# http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

	before_filter :authorize, only: [:edit, :update, :new]

	def index
		# @cards = Card.all
		@cards = Card.order("subject").page(params[:page]).per(5)
	end

	def edit
		@card = Card.find(params[:id])
	end

	def new
		@card = Card.new
	end

	def create
		@card = Card.new(card_params)

		if @card.save
			redirect_to @card
		else
			render 'new'
		end
	end

	def show
		@card = Card.find(params[:id])
	end

	def update
		@card = Card.find(params[:id])

		if @card.update(card_params)
			redirect_to @card
			#  if @article.update_attributes(params[:article])
			# redirect_to @article, notice: "Article has been updated."
		else
			render 'edit'
		end
	end

	def destroy
		@card = Card.find(params[:id])
		@card.destroy

		redirect_to cards_path
	end

	private
	def card_params
		params.require(:card).permit(:subject, :content, :fact, :references)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	# http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

	def create
		@card = Card.find(params[:card_id])
		@comment = @card.comments.create(comment_params)
		redirect_to card_path(@card)
	end

	def destroy
		@card = Card.find(params[:card_id])
		@comment = @card.comments.find(params[:id])
		@comment.destroy
		redirect_to card_path(@card)
	end

	private
	def comment_params
		params.require(:comment).permit(:commenter, :body)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_url, notice: "Logged in!"
		else
			flash.now.alert = "Email or password is invalid."
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, notice: "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "P@ssw0rd!", only: :destroy


  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :salt, :encrypted_password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@card = Card.order("rand()").limit(1)
	end

	def show
		redirect_to card_path(Card.last) and return
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/_card.html.erb
<p>
  <strong>Content:</strong>
  <%= card.content %>
</p>

<p>
  <strong>Fact:</strong>
  <%= card.fact %>
</p>

app/views/cards/_form.html.erb
<%= form_for @card do |f| %>
  <% if @card.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>
    
    <ul>
    <% @card.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %>
    <p class="user_input">
      <%= f.text_field :subject %>
    </p>

    <%= f.label :content %>
    <p class="user_input">
      <%= f.text_field :content %>
    </p>
  </div>
 
  <div class="field">
    <%= f.label :fact %><br>
    <p class="user_input">
      <%= f.text_area :fact %>
    </p>
  </div>
 
  <div class="field">
    <div class="actions"><%= submit_tag "Submit" %>
  </div>

  <div class="field">
    <%= f.label :references %><br>
    <p class="user_input">
      <%= f.url_field :references %>
    </p>
  </div>
<% end %>

app/views/cards/edit.html.erb
<br>
<br>
<br>
<br>
<h1>Editing Card</h1>
 
<%= render 'form' %>

app/views/cards/index.html.erb
<%= paginate @cards %>

<h1>Listing Cards</h1>

<table>
  <tr>
    <th>Subject</th>
    <th>Content</th>
    <th colspan="3"></th>
  </tr>
  
    <% if @cards.empty? %>
      <td class="noposts">No Cards available</td>
    <% else %>

    <% @cards.each do |card| %>
      <tr>
        <td><%= card.subject %></td>
        <td><%= card.content %></td>
        <td><%= link_to 'Show', card_path(card) %></td>
        <% if current_user %>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card_path(card),
          method: :delete, data: { confirm: 'Are you sure you wish to delete this?' } %></td>
        <% end %>
      </tr>
    <% end %>
  <% end %>
</table>

<%= paginate @cards %>

app/views/cards/new.html.erb
<br>
<br>
<br>
<br>
<h1>New Card Facts</h1>
 
<%= render 'form' %>

app/views/cards/show.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span10">
			<div class="cards">
				<br>
				<br>
				<br>
				<br>
				<p>
			  		<strong>Subject:</strong>
			  		<%= @card.subject %>
				</p>
			 
				<p>
			  		<strong>Content:</strong>
			  		<%= @card.content %>
				</p>

				<p>
			  		<strong>Fact:</strong>
			  		<%= @card.fact %>
				</p>
				<br>
				<br>
				<br>
			</div>
			<br>
			<br>
			<p>
			  <strong>References:</strong>
			  <%= link_to @card.references, @card.references %>
			</p>
		</div>
		<% if current_user %>
			<%= link_to "<button>Edit Card</button>".html_safe, edit_card_path(@card) %>
		<% end %>

		<div class="span2">
			<hr>
			<br>
			<br>
			<div class="comments">
				<h2>Comments</h2>
				<%= render @card.comments %>

				<h2>Add a comment:</h2>
				<%= render "comments/form" %>
			</div>
		</div>
	</div>
</div>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<% if current_user %>
<p>
  <%= link_to 'Destroy Comment', [comment.card, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@card, @card.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br>
    <p class="user_input">
      <%= f.text_field :commenter %>
    </p>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <p class="user_input">
      <%= f.text_area :body %>
    </p>
  </div>
  <div class="actions"><%= submit_tag "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FactCards" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-static-top">
          <div id="user">
            <% if current_user %>
            Logged in as <%= current_user.email %>
            <% end %>
          </div>
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/welcome">FactCards</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Users", "/users"  %></li>
            <% if current_user %>
            <li><%= link_to "Log Out", "/logout"  %></li>
            <% else %>
            <li><%= link_to "Sign Up", "/signup"  %></li>
            <li><%= link_to "Log In", "/login"  %></li>
            <% end %>
            <% if current_user %>
            <li><%= link_to "All Cards", "/cards"  %></li>
            <li><%= link_to "New Card", new_card_path  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>


  <center>
    <div class="container-fluid">
      <%= yield %>
    </div> <!-- /container -->
  </center>

  </body>
</html>

app/views/users/index.html.erb
<br>
<br>
<br>
<br>
<table>
  <tr>
    <th>All Users Listed</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <% if current_user %>
      <td>
        <%= link_to 'Remove User', user_path(user),
        method: :delete, 
        data: { confirm: 'Are you sure?' } %>
      </td>
      <% end %>
    </tr>
  <% end %>
  </table>

app/views/users/new.html.erb
<br>
<br>
<br>
<br>
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <p class="user_input">
      <%= f.text_field :email %>
    </p>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <p class="user_input">
      <%= f.password_field :password %>
    </p>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <p class="user_input">
      <%= f.password_field :password_confirmation %>
    </p>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/welcome/index.html.erb
<br>
<br>
<br>
<br>
<h1>Welcome to my Fact Card app!</h1>
<h2>Click above on "All Cards" to view more facts.</h2>
<div class="welcome_card">
	<br>
	<br>
	<br>
	<br>
	<%= render partial: 'cards/card', locals: { card: Card.last } %>
	<br>
	<br>
	<br>
</div>